;;   ------------------ 3.1.l ------------------
;;
;;				created by: parker johnson
;;				date completed: sept 17 4:00 a.m.
;;
;;   HONOR PLEDGE:
;;		    I, parker johnson, pledge that this and confirms
;;		    to SPCA.
;;					parker johnson
;;
;;-------------------------------------------------
;problem 3-1 EXCHANGE.  returns the elements of a two element
;list in reverse order

(defun exchange (a)
  (reverse a) )

;example input
;(setf sinners '(adam eve))
;(exchange sinners)
