;;   ------------------ 4.2.l ------------------
;;
;;				created by: parker johnson
;;				date completed: sept 17 4:00 a.m.
;;
;;   HONOR PLEDGE:
;;		    I, parker johnson, pledge that this and confirms
;;		    to SPCA.
;;					parker johnson
;;
;;-------------------------------------------------

;; PALINDROMEP   4-2

(defun palindromep (a)
  (equal a (reverse a) ) )

;sample input:
;(palindromep '(a b c b a) )
;(palindromep '(a b c c b a) )
;(palindromep '(a b c c c a) )

