;;   ------------------ 4.4.l ------------------
;;
;;				created by: parker johnson
;;				date completed: sept 17 4:00 a.m.
;;
;;   HONOR PLEDGE:
;;		    I, parker johnson, pledge that this and confirms
;;		    to SPCA.
;;					parker johnson
;;
;;-------------------------------------------------

; evaluate the following  4-4

(and (listp pi) (setf result 'set-in-first-and))

(and (numberp pi) (setf result 'set-in-second-and))
